services:
  mosquitto:
    image: docker.io/library/eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:z
      - ./mosquitto/log/:/mosquitto/log/:z
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - mqtt_listener_nw
  keycloak:
    image: localhost/test_kc_event_listener
    build:
      context: ../
      dockerfile: ./testing/Dockerfile
      args: "KEYCLOAK_VERSION=$KEYCLOAK_VERSION"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=kcadmin
      - DB_VENDOR=h2
      - KC_HTTP_PORT=8082
      - KC_HEALTH_ENABLED=true
    command:
      - "start-dev"
      - "--spi-events-listener-mqtt-server-uri=\"tcp://mosquitto:1883\""
      - "--spi-events-listener-mqtt-username=mqtt"
      - "--spi-events-listener-mqtt-password=mqtt"
      - "--spi-events-listener-mqtt-topic=keycloak"
    ports:
      - "8082:8082"
    networks:
      - mqtt_listener_nw
networks:
  mqtt_listener_nw:
    driver: bridge
